name: Unity Test

on:
  push:
    branches: [package, main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  tests:
    name: Unity Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectPath: ["./"]
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Run Tests
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: ${{ matrix.projectPath }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactsPath: test-results

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unity-test-results
          path: test-results
